### PR TITLE
[VERY MUCH IMPORTANT] [AND I MEAN VERY] build: ensure appropriate naming conventions for build system

### PR DESCRIPTION
**Pull request by q009**
This makes sure that the project follows proper naming conventions set by modern standards and widely followed by many developers worldwide. As such, this change is to be considered mandatory if it wishes stay competitive.

### CODE REVIEW

**Comment by q009** [comment]
Please merge.

**Review by no-lex — CHANGES_REQUESTED** [review]
This commit does not appear to be passing the CI. If you could resolve this issue, that would be great. Common mistakes:
- Missing semicolons after code lines
- Not defining each variable separately in macro bodies
- Failing to include the correct header files
- Using features not included in C++17
- Failing to include new files in the Makefile

**Comment by no-lex** [comment]
Please update this PR to resolve the aformentioned issue(s) or I will be closing it.

**Comment by no-lex** [comment]
Inane bikeshedding.

**Pull request closed without merging**
